version: '3'
services:
  php-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/api/swagger.yml
    volumes:
      - ./swagger.yml:/api/swagger.yml
    depends_on:
      - php-api
      
  cors-proxy:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-api      